# Import 

In [5]:
import numpy as np

#  1.Creating Numpy Arrays from Python List 

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
[3.14,1,2,3]

[3.14, 1, 2, 3]

In [4]:
np.array([3.14,1,2,3]) #Se chuyen tat ca Data ve Data Type Float

array([3.14, 1.  , 2.  , 3.  ])

In [5]:
np.array([1,2,3,4], dtype = 'float32') #Cu the hoa Data Type 

array([1., 2., 3., 4.], dtype=float32)

In [6]:
a1 = np.array([1,2,3,4])

In [7]:
type(a1)

numpy.ndarray

In [9]:
a2 = np.array([[1,2,3,4],
               [5,6,7,8]])

In [10]:
type(a2)

numpy.ndarray

In [11]:
a2.shape #Cho biet co bao nhieu dong va bao nhieu cot

(2, 4)

In [12]:
a2.ndim #So chieu cua Mang  

2

In [13]:
a2.dtype #Data type 

dtype('int32')

In [14]:
a2.size #Tong thanh phan cua bang (1,2,3,4,5,6,7,8)

8

# 2. Creating Numpy Arrays from Scratch

### zeros,ones,full,arange,linspace

In [15]:
np.zeros([2,3,4],dtype = int) #Bam shift + Tab de coi #2 lan 3 dong 4 cot 

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [16]:
np.ones([3,5],dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
np.full([3,5], 27.12)

array([[27.12, 27.12, 27.12, 27.12, 27.12],
       [27.12, 27.12, 27.12, 27.12, 27.12],
       [27.12, 27.12, 27.12, 27.12, 27.12]])

In [19]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### Random

In [20]:
np.random.random((3,5)) #Chi nam tu 0 den 1 

array([[0.60584713, 0.96411599, 0.21065228, 0.77904743, 0.49171268],
       [0.34757122, 0.00417918, 0.61245997, 0.90585475, 0.12719937],
       [0.05342951, 0.51636518, 0.74092148, 0.74046272, 0.38064122]])

In [22]:
# Seed for reproducibility
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [ ]:
np.random.rand(4,4)

In [23]:
np.random.normal(0,1, (3,3))

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [24]:
np.random.randint(12,27,(4,4))

array([[19, 24, 14, 12],
       [12, 16, 17, 17],
       [18, 20, 16, 13],
       [16, 21, 22, 22]])

# 3.Array Indexing & Slicing 

### One-Dimensional subarray

In [25]:
x1 = np.random.randint(20,size = 6)

In [26]:
x1

array([1, 1, 7, 9, 3, 6])

In [27]:
x1[4] #Truy van toi bien so 4 (Python tinh tu 0) nen truong hop nay se tra ve so 3

3

In [28]:
x1[-1] #Truy van toi vi tri cuoi cung

6

### Multi-Dimensional Array

In [29]:
x2 = np.random.randint(10,size = (3,5))

In [30]:
x2

array([[7, 2, 0, 3, 5],
       [9, 4, 4, 6, 4],
       [4, 3, 4, 4, 8]])

In [31]:
x2 [0,2] #Dong truoc,cot sau

0

In [32]:
x2 [0,2] = 9

In [33]:
x2

array([[7, 2, 9, 3, 5],
       [9, 4, 4, 6, 4],
       [4, 3, 4, 4, 8]])

### Slicing

In [34]:
x1

array([1, 1, 7, 9, 3, 6])

In [35]:
x1[0:3]

array([1, 1, 7])

In [36]:
x1[2:4]

array([7, 9])

In [38]:
x1[::2] #Cat 2 step

array([1, 7, 3])

In [39]:
x2

array([[7, 2, 9, 3, 5],
       [9, 4, 4, 6, 4],
       [4, 3, 4, 4, 8]])

In [40]:
x2[:2,:3] #Dong dau tien

array([[7, 2, 9],
       [9, 4, 4]])

In [41]:
x2 [:,3] # : Include all

array([3, 6, 4])

# 4.Reshaping of Arrays & Transpose

In [42]:
grid = np.arange(1,10)
grid.shape

(9,)

In [44]:
grid.reshape((3,3)) #Goi ra 1 Matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Transpose

In [45]:
x = np.array(([1.,2.],[3.,4,]))

In [46]:
x

array([[1., 2.],
       [3., 4.]])

In [47]:
x.T #Transpose: chuyen hanh thanh cot 

array([[1., 3.],
       [2., 4.]])

# 5 Array concatenation and Splitting

In [48]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [49]:
np.concatenate((x,y)) #Ham noi 

array([1, 2, 3, 4, 5, 6])

In [51]:
grid = np.array([[1,2,3],
                 [4,5,6]])

In [52]:
np.concatenate((grid,grid))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [55]:
np.concatenate((grid,grid),axis = 1) #0 la doc,1 la ngang


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [56]:
#Vstack noi doc
x = np.array([1,2,3])
grid = np.array ([[9,8,7],
                  [6,5,4]])

In [57]:
np.vstack((x,grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [58]:
#Hstack noi ngang
y = np.array([[99],
              [99]])

In [59]:
np.hstack((y,grid))

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

 ### Splitting of Arrays

In [6]:
x = np.array([1,2,3,99,69,3,2,1])

In [7]:
x1,x2,x3 = np.split(x,[3,5]) #Tach thanh 3 Arrays

In [8]:
x1

array([1, 2, 3])

In [9]:
x2

array([99, 69])

In [10]:
x3

array([3, 2, 1])

In [11]:
np.info(x3)

class:  ndarray
shape:  (3,)
strides:  (4,)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x24f19350804
byteorder:  little
byteswap:  False
type: int32


# 6 Broadcasting and Vectorize operations

In [12]:
a = np.arange(3)
a

array([0, 1, 2])

In [14]:
a + 5 #Broadcasting

array([5, 6, 7])

In [15]:
b = np.ones((3,3))

In [16]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
a.shape, b.shape #a la bang 1 chieu (1 dong 3 cot) b la bang 2 chieu(3 dong 3 cot)

((3,), (3, 3))

In [18]:
a + b 

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [19]:
a * b  

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [20]:
c  = np.arange(3).reshape((3,1))

In [21]:
c

array([[0],
       [1],
       [2]])

In [22]:
d = np.arange(3)

In [25]:
d.T #Transpose ?? Why don't work

array([0, 1, 2])

In [26]:
c

array([[0],
       [1],
       [2]])

In [27]:
a+c #a la columns b la rows. 2 cai khac size nhau 

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

# 7 Manipulating & Comparing Arrays

### Aggregation 

In [29]:
list_number = [1,2,3] #Tao gia tri

In [30]:
ll = np.array(list_number) #Gan gia tri

In [31]:
ll #Print gia tri

array([1, 2, 3])

In [32]:
sum(ll) #Sum python

6

In [33]:
np.sum(ll) #Sum Numpy 

6

In [34]:
massive_array = np.random.random(10000) #Create a big data

In [35]:
massive_array[:5] #Hien thi 5 so dau tien

array([0.27088801, 0.7204714 , 0.58725827, 0.2800492 , 0.99565522])

In [36]:
massive_array.shape #Shape: 10000 va 1 chieu

(10000,)

In [37]:
%timeit sum(massive_array) #Ham timeit coi thoi gian 1 cau lenh se chay mat bao nhieu thoi gian 
%timeit np.sum(massive_array)

1.72 ms ± 39.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
16.8 µs ± 864 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [38]:
# Important for Data Science and Machine Learning 

In [39]:
np.mean(massive_array) #Trung binh

0.4954661154693555

In [42]:
np.max(massive_array) #Max and Min

0.9998753694136024

In [41]:
np.min(massive_array)

0.000144853151614166

### Standard Deviation and Variance

In [43]:
dog_height = [600,470,170,430,300]

In [44]:
dog_height = np.array(dog_height)

In [45]:
np.std(dog_height)

147.32277488562318

In [46]:
np.var(dog_height)

21704.0

In [47]:
np.sqrt(np.var(dog_height))

147.32277488562318

### Sorting Arrays

In [48]:
# np.sort uses an quicksort algorithm

In [49]:
x = np.array([2,1,4,5,3])

In [50]:
np.sort(x) #Sap xep theo thu tu

array([1, 2, 3, 4, 5])

In [52]:
np.argsort(x) #Sap xep theo vi tri (Vd: so 2 nam o vi tri 0)

array([1, 0, 4, 2, 3], dtype=int64)

### Sorting Arrays Rows and Cloumns

In [53]:
np.random.seed(42)
MatA = np.random.randint(0,10 ,size=(4,6))

In [54]:
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [55]:
np.sort(MatA,axis =0) #Sap xep theo chieu doc(cloumns)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [56]:
np.sort(MatA,axis =1) #Sap xep theo chieu ngang(rows)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

# 8 Linear Algebra

In [57]:
#Dai so tuyen tinh

In [59]:
A = np.array([[1,2,3], #3x3
             [4,5,6],
             [7,8,9]])

In [63]:
B = np.array([[1,2], #3x2
             [3,4],
             [5,6]])

In [64]:
A.dot(B) #Tich vo huong 

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

In [65]:
A @ B #Cach 2

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

In [66]:
# Ma tran phai cung so chieu 
B.T #tu (3x3) thanh (2x3)

array([[1, 3, 5],
       [2, 4, 6]])

In [67]:
B.T @ A 

array([[48, 57, 66],
       [60, 72, 84]])

### Dot Product Example

In [69]:
np.random.seed(0)
sales_amounts = np.random.randint(20,size =(5,3))

In [70]:
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [71]:
import pandas as pd

In [80]:
weekly_sales = pd.DataFrame(sales_amounts, index = ['Mon','Tue','Wed','Thurs','Fri'],
                           columns = ['Almond Peanut','Peanut Butter','Cashew Butter'])

In [81]:
weekly_sales

Almond Peanut  Peanut Butter  Cashew Butter
Mon               12             15              0
Tue                3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [83]:
# Create a price array 
prices = np.array([10,8,12])

In [124]:
butter_prices = pd.DataFrame(prices.reshape(1,3),index = ["Price"],columns = ['Almond Peanut','Peanut Butter','Cashew Butter'])

In [86]:
butter_prices

Almond Peanut  Peanut Butter  Cahsew Butter
Price             10              8             12

In [117]:
weekly_sales.shape,butter_prices.T.shape

((5, 3), (3, 1))

In [125]:
butter_prices.T

Price
Almond Peanut     10
Peanut Butter      8
Cashew Butter     12

In [126]:
total_prices = weekly_sales.dot(butter_prices.T)

In [127]:
total_prices

Price
Mon      240
Tue      138
Wed      458
Thurs    232
Fri      142

In [129]:
weekly_sales['Total Price'] = total_prices

In [131]:
weekly_sales

Almond Peanut  Peanut Butter  Cashew Butter  Total Price
Mon               12             15              0          240
Tue                3              3              7          138
Wed                9             19             18          458
Thurs              4              6             12          232
Fri                1              6              7          142

#  9 ENDING 

### Python Data Science Handbook Chapter 2 